namespace MariesWonderland.Models.Type;

public enum AbnormalBehaviourActionType
{
    UNKNOWN = 0,
    DAMAGE = 1,
    TURN_RESTRICTION = 2,
    ATTRIBUTE_DAMAGE_CORRECTION = 3,
    RECOVERY = 4,
    HIT_RATIO_DOWN = 5,
    DEFAULT_SKILL_LOTTERY_CORRECTION = 6,
    DAMAGE_MULTIPLY = 7,
    ABNORMAL_RESISTANCE = 8,
    BUFF_RESISTANCE = 9,
    OVERRIDE_HIT_EFFECT = 10,
    MODIFY_HATE_VALUE = 11,
    UNDEAD = 12,
    OVERRIDE_EVASION_VALUE = 13
}
