namespace MariesWonderland.Models.Type;

public enum CostumeAutoOrganizationConditionType
{
    UNKNOWN = 0,
    RECOVERY_COEFFICIENT_FIRE = 1,
    RECOVERY_COEFFICIENT_WATER = 2,
    RECOVERY_COEFFICIENT_WIND = 3,
    RECOVERY_COEFFICIENT_LIGHT = 4,
    RECOVERY_COEFFICIENT_DARK = 5,
    ATTACKER_IGNORE_TARGET = 6
}
