namespace MariesWonderland.Models.Type;

public enum GimmickType
{
    UNKNOWN = 0,
    CAGE_TREASURE_HUNT = 1,
    CAGE_INTERVAL_DROP_ITEM = 2,
    BROKEN_OBELISK = 3,
    IRON_GRILL = 4,
    RADIO_MESSAGE = 5,
    FIRST_BROKEN_OBELISK = 6,
    MAP_ONLY_CAGE_TREASURE_HUNT = 7,
    MAP_ONLY_CAGE_INTERVAL_DROP_ITEM = 8,
    REPORT = 9,
    CAGE_MEMORY = 10,
    MAP_ONLY_HIDE_OBELISK = 11
}
