namespace MariesWonderland.Models.Type;

public enum MaterialType
{
    UNKNOWN = 0,
    WEAPON_ENHANCEMENT = 10,
    COSTUME_ENHANCEMENT = 20,
    COMPANION_ENHANCEMENT = 30,
    WEAPON_SKILL_ENHANCEMENT = 40,
    COSTUME_SKILL_ENHANCEMENT = 50,
    COMMON_SKILL_ENHANCEMENT = 60,
    WEAPON_EVOLUTION = 70,
    WEAPON_LIMIT_BREAK = 80,
    COSTUME_LIMIT_BREAK = 90,
    CHARACTER_BOARD_RELEASE = 100,
    COSTUME_AWAKEN = 110,
    CHARACTER_REBIRTH = 120,
    WEAPON_AWAKEN = 130,
    COSTUME_LOTTERY_EFFECT_UNLOCK = 140
}
