namespace MariesWonderland.Models.Type;

public enum StatusChangeType
{
    UNKNOWN = 0,
    AGILITY_ADD = 1,
    AGILITY_MULTIPLY = 2,
    ATTACK_ADD = 3,
    ATTACK_MULTIPLY = 4,
    CRITICAL_ATTACK_ADD = 5,
    CRITICAL_ATTACK_MULTIPLY = 6,
    CRITICAL_RATIO_ADD = 7,
    CRITICAL_RATIO_MULTIPLY = 8,
    EVASION_RATIO_ADD = 9,
    EVASION_RATIO_MULTIPLY = 10,
    HP_ADD = 11,
    HP_MULTIPLY = 12,
    VITALITY_ADD = 13,
    VITALITY_MULTIPLY = 14
}
