namespace MariesWonderland.Models.Type;

public enum TipDisplayConditionType
{
    UNKNOWN = 0,
    DEFAULT = 1,
    COMEBACK_DAYS = 2,
    TIP_ID_DISPLAYED_ON_THE_SAME_DAY = 3,
    TIP_ID_NOT_DISPLAYED_ON_THE_SAME_DAY = 4,
    QUEST_CLEAR = 5,
    FRIEND_COUNT = 6,
    QUEST_NOT_CLEAR = 7,
    TIP_ID_DISPLAYED = 8,
    TIP_ID_NOT_DISPLAYED = 9,
    TIP_BACKGROUND_ASSET_ID_DISPLAYED_ON_THE_SAME_DAY = 10,
    TIP_BACKGROUND_ASSET_ID_NOT_DISPLAYED_ON_THE_SAME_DAY = 11,
    TIP_BACKGROUND_ASSET_ID_DISPLAYED = 12,
    TIP_BACKGROUND_ASSET_ID_NOT_DISPLAYED = 13,
    USER_CURRENT_SEASON_ID = 14,
    USER_CURRENT_ROUTE_ID = 15
}
