namespace MariesWonderland.Models.Type;

public enum TipSituationType
{
    UNKNOWN = 0,
    DEFAULT = 1,
    ASSET_INITIAL_DOWNLOAD = 2,
    AFTER_LOSED_BATTLE = 3,
    TRANSITION_BATTLE = 4,
    TITLE = 5,
    TRANSITION_QUEST_BY_SEASON_ID = 6,
    TRANSITION_QUEST_BY_MAIN_CHAPTER_ID = 7,
    TRANSITION_QUEST_BY_EVENT_CHAPTER_ID = 8,
    TRANSITION_CAGE_BY_SEASON_ID = 9
}
